### ISSUE TITLE
Potentially Switch Build Systems?

### ISSUE THREAD

**Issue by tomeichlersmith** [JeffersonLab/hps-align#22]
I have some experience writing python packages and could convert the current setup from a CMake-based build system to a python-setuptools one. This would make using the python scripts and the modules they are based on more ergonomic; however, it would restrict us to python scripts. I don't forsee us using anything but python in this repository, but I don't want to waste time performing this update if it isn't going to be merged. Any interest @cbravo135 @sarahgaiser ?

For context, I would imagine something similar to [hps-mille/align](https://github.com/tomeichlersmith/hps-mille/tree/main/align) where the CLI could be auto-generated by [typer](https://typer.tiangolo.com/) and one could either install a frozen version with `pip install`, install an editable/developer version with `pip install -e`, or the package directly from this source repo.

**Comment by sarahgaiser** [comment]
I'm happy to switch build systems! I don't think we will be adding non-python code to this repo but maybe @cbravo135 and @pbutti could comment on this.

**Comment by tomeichlersmith** [comment]
For using NumPy-style doc strings https://numpydoc.readthedocs.io/en/latest/format.html#docstring-standard if we want to switch to using Sphinx to generate our doc html rather than doxygen.
